<?xml version="1.0" encoding="utf-8"?><Database Name="QLTHUVIEN" Class="QLTHUVIENDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-9Q61PN6\SQLEXPRESS;Initial Catalog=QLTHUVIEN;Integrated Security=True" SettingsObjectName="TG.Properties.Settings" SettingsPropertyName="QLTHUVIENConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Sach" Member="Saches">
    <Type Name="Sach">
      <Column Name="MaSach" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSach" Type="System.String" DbType="NChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaTacGia" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NamXuatBan" Type="System.String" DbType="Char(4)" CanBeNull="true" />
      <Column Name="ViTri" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="SoLuongConLai" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TacGia_Sach" Member="TacGia" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="TacGia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TacGia" Member="TacGias">
    <Type Name="TacGia">
      <Column Name="MaTacGia" Type="System.String" DbType="Char(4) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="TacGia_Sach" Member="Saches" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="Sach" />
    </Type>
  </Table>
</Database>