//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTra
    {
        public string IDSach { get; set; }
        public string IDDocGia { get; set; }
        public System.DateTime NgayGiaoDich { get; set; }
        public string HanhDong { get; set; }
    
        public virtual DocGia DocGia { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
