//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sach
    {
        public string MaSach { get; set; }
        public string TenSach { get; set; }
        public string MaTacGia { get; set; }
        public string TenTheLoai { get; set; }
        public string NamXuatBan { get; set; }
        public string ViTri { get; set; }
        public int SoLuongConLai { get; set; }
    
        protected virtual TacGia TacGia { get; set; }
    }
}
