//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MuonTra
    {
        public int MaMuonTra { get; set; }
        public string MaSach { get; set; }
        public Nullable<int> SoThe { get; set; }
        public string MaNhanVien { get; set; }
        public System.DateTime NgayMuon { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Da_Tra { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
    
        public virtual QuanLy QuanLy { get; set; }
        public virtual Sach Sach { get; set; }
        public virtual TheThuVien TheThuVien { get; set; }
    }
}
